server:
  port: 8080

spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank account"
  contactDetails:
    name: "Shubham Dev"
    email: "shubham@dev"
  onCallSupport:
    - (111)111-1234
    - (111)111-5678





